### ISSUE TITLE
waitUntil throws exception however keeps on running the predicate

### ISSUE THREAD

**Issue by johnjiang** [devlato/async-wait-until#14]
**Describe the bug**
When I use a predicate with a timeout and interval, an exception is correctly thrown after the timeout but the predicate is still being executed.

**To Reproduce**
https://codesandbox.io/s/vigilant-dust-c3119?file=/src/index.js

```
import { waitUntil } from "async-wait-until";

(() => {
  waitUntil(
    () => {
      console.log("Trying");
      return Promise.resolve(false);
    },
    { timeout: 1000, intervalBetweenAttempts: 100 }
  );
})();
```

**Expected behavior**
Exception is thrown and the predicate no longer runs. However, the exception is thrown but the predicate is still being executed

**Comment by devlato** [comment]
Thanks for reporting @johnjiang! I'll push the fix shortly.

**Comment by johnjiang** [comment]
Thanks for fixing it so quickly!

**Comment by devlato** [comment]
No worries!
