### ISSUE TITLE
[Bug Report] Latest release (2.0.10) is broken

### ISSUE THREAD

**Issue by rossng** [devlato/async-wait-until#29]
**Describe the bug**

The latest version of `async-wait-until` is broken - it contains no code assets.

<img width="160" alt="image" src="https://user-images.githubusercontent.com/565371/147671512-8f1b632e-c40b-4e85-b103-d59bf2c7e876.png">

**To Reproduce**

1. Update to `async-wait-until@2.0.10`
2. See compiler/IDE error.

**Expected behavior**

N/A

**Screenshots**

**Additional context**

**Comment by ViktorMasnyi** [comment]
Hi, I have issues with 2.0.10 either.

**Comment by maicol07** [comment]
I confirm this issue too. The `dist` folder is missing: probably a mistake when publishing the new release to the npm registry?

**Comment by eliteSchwein** [comment]
i can confirm this issue too.

**Comment by devlato** [comment]
Thanks for reporting @rossng, @ViktorMasnyi, @maicol07, and @eliteSchwein! The fix will be released in `2.0.12` ASAP.

**Comment by devlato** [comment]
@rossng @ViktorMasnyi @maicol07 @eliteSchwein hey folks, the fix's just been published as `2.0.12`.

**Comment by rossng** [comment]
Thanks @devlato!
